NationalLibraryOfNorway/warehouse-logistics-service

- .github/workflows/deploy-project.yaml
Add the missing file input to the `docker/build-push-action@v5` action which is needed after moving the `Dockerfile` to the `docker` folder
> HotFix: Fix the Docker image build step

- src/main/kotlin/no/nb/mlt/wls/product/controller/ProductController.kt
- src/main/kotlin/no/nb/mlt/wls/product/payloads/ApiProductPayload.kt
- src/main/kotlin/no/nb/mlt/wls/product/service/ProductService.kt
Change how we handle the location and quantity in the product endpoint. We used to receive them as is and forward them to the database and other places. That does not make sense as the catalogue does not decide the quantity nor the location. Now the endpoint ignores them and overrides these fields with default values.
The swagger doc reflects the change by making those two fields read only.
> MLT-0028 fix error in product creation

- src/main/kotlin/no/nb/mlt/wls/core/data/synq/SynqOwner.kt
- src/main/kotlin/no/nb/mlt/wls/order/model/Order.kt
- src/main/kotlin/no/nb/mlt/wls/order/payloads/ApiOrderPayload.kt
- src/main/kotlin/no/nb/mlt/wls/order/payloads/SynqOrderPayload.kt
- src/main/kotlin/no/nb/mlt/wls/product/payloads/ApiProductPayload.kt
- src/main/kotlin/no/nb/mlt/wls/product/payloads/SynqProductPayload.kt
This PR introduces the draft of data structures which will represent orders in Hermes MLT, this includes both the main model class Order which will be stored in our database as well as the payload classes for API and SynQ.
There are quite a few questions and things we need to discuss in the team (and perchance outside the team) about some things related to the order. For more info see the code and Jira task
> MLT-0022 Define datastructure for orders

- pom.xml
- src/main/kotlin/no/nb/mlt/wls/core/data/synq/SynqError.kt
- src/main/kotlin/no/nb/mlt/wls/order/service/OrderService.kt
- src/main/kotlin/no/nb/mlt/wls/order/service/SynqOrderService.kt
- src/main/kotlin/no/nb/mlt/wls/product/exceptions/DuplicateProductException.kt
- src/main/kotlin/no/nb/mlt/wls/product/service/ProductService.kt
- src/main/kotlin/no/nb/mlt/wls/product/service/SynqProductService.kt
- src/test/kotlin/no/nb/mlt/wls/product/controller/ProductControllerTest.kt
- src/test/kotlin/no/nb/mlt/wls/product/service/ProductServiceTest.kt
This PR refactors the codebase to achieve even further reactive handling. It makes the following improvements:
- Properly throw exceptions when the service times out
- Unify the handling of errors from SynQ between all services
- Streamline exception handling using more reactive code
> MLT-0040 More reactive handling

- src/main/kotlin/no/nb/mlt/wls/order/repository/OrderRepository.kt
- src/main/kotlin/no/nb/mlt/wls/order/service/OrderService.kt
- src/test/kotlin/no/nb/mlt/wls/order/controller/OrderControllerTest.kt
- src/test/kotlin/no/nb/mlt/wls/order/model/OrderModelConversionTest.kt
- src/test/kotlin/no/nb/mlt/wls/order/service/OrderServiceTest.kt
- src/test/kotlin/no/nb/mlt/wls/product/model/ProductModelConversionTest.kt
Adds a some tests for OrderService
Has one breaking change with renaming `getByHostNameAndHostOrderId` to `findByHostNameAndHostOrderId` in OrderRepository, to be more consistent with ProductRepository
> MLT-0032 Tests for OrderService

- src/main/kotlin/no/nb/mlt/wls/order/controller/OrderController.kt
- src/main/kotlin/no/nb/mlt/wls/order/service/OrderService.kt
- src/main/kotlin/no/nb/mlt/wls/order/service/SynqOrderService.kt
- src/main/kotlin/no/nb/mlt/wls/product/controller/ProductController.kt
- src/main/kotlin/no/nb/mlt/wls/product/service/ProductService.kt
- src/test/kotlin/no/nb/mlt/wls/order/controller/OrderControllerTest.kt
This pull requests aims to make handling of duplicate orders similar to the way we handle duplicate products.
It comes with the same weakness in case SynQ informs us that the order is a duplicate, not our DB. Problem being we have no information about the order and no way of getting that information through API.
> MLT-41 Change handling of duplicate orders

- src/main/kotlin/no/nb/mlt/wls/order/controller/OrderController.kt
- src/main/kotlin/no/nb/mlt/wls/order/model/Order.kt
- src/main/kotlin/no/nb/mlt/wls/order/payloads/ApiUpdateOrderPayload.kt
- src/main/kotlin/no/nb/mlt/wls/order/payloads/SynqOrderPayload.kt
- src/main/kotlin/no/nb/mlt/wls/order/service/OrderService.kt
- src/main/kotlin/no/nb/mlt/wls/order/service/SynqOrderService.kt
- src/test/kotlin/no/nb/mlt/wls/order/service/OrderServiceTest.kt
Adds an API endpoint for updating existing orders
> MLT-0043 Update Order (PUT) endpoint

- src/test/kotlin/no/nb/mlt/wls/order/controller/OrderControllerTest.kt
- src/test/kotlin/no/nb/mlt/wls/order/service/OrderServiceTest.kt
- src/test/kotlin/no/nb/mlt/wls/product/controller/ProductControllerTest.kt
- src/test/kotlin/no/nb/mlt/wls/product/service/ProductServiceTest.kt
A small thing on the side I have been preparing until all the endpoints were merged into main. This contains tests for the GET, UPDATE, and DELETE endpoints.
> Controller Test Improvements

- docker/keycloak/import/mlt-local-realm-export.json
This is a small fix that updates the hidden CORS fields for Keycloak (can be shown by enabling a standard flow temporarily) to allow for any origin while testing locally
> Update Keycloak Origins for Axiell test client

- src/main/kotlin/no/nb/mlt/wls/application/restapi/item/ProductController.kt
- src/main/kotlin/no/nb/mlt/wls/domain/WLSService.kt
- src/main/kotlin/no/nb/mlt/wls/domain/ports/inbound/ItemNotFoundException.kt
- src/main/kotlin/no/nb/mlt/wls/domain/ports/inbound/MoveItem.kt
- src/main/kotlin/no/nb/mlt/wls/domain/ports/inbound/UpdateOrder.kt
- src/main/kotlin/no/nb/mlt/wls/domain/ports/inbound/ValidationException.kt
- src/main/kotlin/no/nb/mlt/wls/domain/ports/outbound/ItemRepository.kt
- src/main/kotlin/no/nb/mlt/wls/infrastructure/repositories/item/MongoItemRepository.kt
- src/test/kotlin/no/nb/mlt/wls/domain/WLSServiceTest.kt
Originally planned as updating items - this PR implements the functionality to move items within WLS. This specific use-case is required for when the storage systems gives us various status updates when the items are withdrawn, inserted, or generally moved around
> MLT-0053 Add use-case for moving items

- src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqBatchItemUpdatePayload.kt
- src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqBatchMoveItemPayload.kt
- src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqController.kt
- src/main/kotlin/no/nb/mlt/wls/domain/WLSService.kt
- src/main/kotlin/no/nb/mlt/wls/domain/ports/inbound/MoveItem.kt
- src/main/kotlin/no/nb/mlt/wls/infrastructure/callbacks/InventoryNotifierAdapter.kt
- src/main/kotlin/no/nb/mlt/wls/infrastructure/repositories/item/MongoItemRepository.kt
- src/test/kotlin/no/nb/mlt/wls/domain/WLSServiceTest.kt
Sends notifications using the webhook for Item Notifications
> MLT-0049 Item Callback

- src/main/kotlin/no/nb/mlt/wls/infrastructure/callbacks/InventoryNotifierAdapter.kt
- src/main/kotlin/no/nb/mlt/wls/infrastructure/callbacks/NotificationItemPayload.kt
A small PR to address an inconsistency with the data structures for the notification handling - This adds a payload specifically for the notifications, so that we have the structure in place to change it in the future
> Item Notification Payload

- src/main/kotlin/no/nb/mlt/wls/application/hostapi/item/ItemController.kt
- src/main/kotlin/no/nb/mlt/wls/application/hostapi/order/OrderController.kt
- src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqController.kt
Adds callback documentation to the controllers, explaining what the response looks like.
One remaining question is whether we add this to some of the other controllers. Currently the only endpoints that produce the callbacks have received the annotation. Should the `createOrder` and `createItem` also be annotated?
> MLT-0060 Create Swagger documentation for Item and Order callbacks

- src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqController.kt
- src/main/kotlin/no/nb/mlt/wls/infrastructure/synq/SynqOrderPayload.kt
- src/main/kotlin/no/nb/mlt/wls/infrastructure/synq/SynqProductPayload.kt
- src/test/kotlin/no/nb/mlt/wls/order/model/OrderModelConversionTest.kt
Prevents order conflicts with multiple hosts.
Remains a draft we decide where it is best to handle the validation for this (likely domain, or should it happen in the service?).
> MLT-0045 Add Hostname on Order IDs for SynQ Orders

- src/main/kotlin/no/nb/mlt/wls/application/hostapi/item/ApiItemPayload.kt
- src/main/kotlin/no/nb/mlt/wls/application/hostapi/item/ItemController.kt
- src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqBatchMoveItemPayload.kt
- src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqController.kt
- src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqOrderPickingConfirmationPayload.kt
- src/main/kotlin/no/nb/mlt/wls/domain/WLSService.kt
- src/main/kotlin/no/nb/mlt/wls/domain/model/Item.kt
- src/main/kotlin/no/nb/mlt/wls/domain/ports/inbound/AddNewItem.kt
- src/main/kotlin/no/nb/mlt/wls/domain/ports/inbound/MoveItem.kt
- src/main/kotlin/no/nb/mlt/wls/domain/ports/inbound/PickItems.kt
- src/main/kotlin/no/nb/mlt/wls/domain/ports/outbound/ItemRepository.kt
- src/main/kotlin/no/nb/mlt/wls/infrastructure/callbacks/NotificationItemPayload.kt
- src/main/kotlin/no/nb/mlt/wls/infrastructure/repositories/item/MongoItem.kt
- src/main/kotlin/no/nb/mlt/wls/infrastructure/repositories/item/MongoItemRepository.kt
- src/test/kotlin/no/nb/mlt/wls/TraillingSlashRedirectTest.kt
- src/test/kotlin/no/nb/mlt/wls/domain/WLSServiceTest.kt
- src/test/kotlin/no/nb/mlt/wls/item/controller/ItemControllerTest.kt
- src/test/kotlin/no/nb/mlt/wls/item/model/ItemModelConversionTest.kt
- src/test/kotlin/no/nb/mlt/wls/item/model/ItemModelValidationTest.kt
- src/test/kotlin/no/nb/mlt/wls/order/controller/OrderControllerTest.kt
- src/test/kotlin/no/nb/mlt/wls/synq/controller/SynqControllerTest.kt
- src/test/kotlin/no/nb/mlt/wls/synq/model/SynqModelConversionTest.kt
- src/test/kotlin/no/nb/mlt/wls/synq/model/SynqModelValidationTest.kt
For our use-cases we do not need doubles for our Item models. This PR refactors this to use integers instead
> MLT-0063 Use Ints for quantity

- docker/compose.yaml
- docker/mongo/mongo-init.js
- src/main/kotlin/no/nb/mlt/wls/application/hostapi/order/ApiOrderPayload.kt
- src/main/kotlin/no/nb/mlt/wls/application/hostapi/order/ApiUpdateOrderPayload.kt
- src/main/kotlin/no/nb/mlt/wls/application/hostapi/order/OrderController.kt
- src/main/kotlin/no/nb/mlt/wls/domain/WLSService.kt
- src/main/kotlin/no/nb/mlt/wls/domain/model/Order.kt
- src/main/kotlin/no/nb/mlt/wls/domain/ports/inbound/CreateOrder.kt
- src/main/kotlin/no/nb/mlt/wls/domain/ports/inbound/UpdateOrder.kt
- src/main/kotlin/no/nb/mlt/wls/infrastructure/callbacks/NotificationOrderPayload.kt
- src/main/kotlin/no/nb/mlt/wls/infrastructure/repositories/order/MongoOrder.kt
- src/main/kotlin/no/nb/mlt/wls/infrastructure/repositories/order/MongoOrderRepositoryAdapter.kt
- src/main/kotlin/no/nb/mlt/wls/infrastructure/synq/SynqOrderPayload.kt
- src/test/kotlin/no/nb/mlt/wls/domain/WLSServiceTest.kt
- src/test/kotlin/no/nb/mlt/wls/order/controller/OrderControllerTest.kt
- src/test/kotlin/no/nb/mlt/wls/order/model/OrderModelConversionTest.kt
- src/test/kotlin/no/nb/mlt/wls/order/model/OrderModelValidationTest.kt
- src/test/kotlin/no/nb/mlt/wls/synq/controller/SynqControllerTest.kt
Replaces Receiver with two new fields in the Order model
> MLT-0075 Order Domain changes

- src/main/kotlin/no/nb/mlt/wls/application/hostapi/item/ApiCreateItemPayload.kt
- src/main/kotlin/no/nb/mlt/wls/application/hostapi/item/ApiItemPayload.kt
- src/main/kotlin/no/nb/mlt/wls/application/hostapi/item/ItemController.kt
- src/main/kotlin/no/nb/mlt/wls/application/hostapi/order/ApiCreateOrderPayload.kt
- src/main/kotlin/no/nb/mlt/wls/application/hostapi/order/OrderController.kt
- src/main/kotlin/no/nb/mlt/wls/infrastructure/callbacks/NotificationItemPayload.kt
This PR removes the unused status field from the order payload when creating orders (MLT-0076). 
It does this by introducing a new payload, `ApiCreateOrderPayload`, which only accepts fields we will actually process (MLT-0083). The latter is also applied for items, via `ApiCreateItemPayload`
> Host API Controller changes

- src/main/kotlin/no/nb/mlt/wls/application/hostapi/item/ApiItemPayload.kt
- src/main/kotlin/no/nb/mlt/wls/domain/model/Item.kt
- src/main/kotlin/no/nb/mlt/wls/domain/ports/inbound/AddNewItem.kt
- src/main/kotlin/no/nb/mlt/wls/infrastructure/callbacks/NotificationItemPayload.kt
- src/main/kotlin/no/nb/mlt/wls/infrastructure/repositories/item/MongoItem.kt
- src/test/kotlin/no/nb/mlt/wls/domain/WLSServiceTest.kt
- src/test/kotlin/no/nb/mlt/wls/item/controller/ItemControllerTest.kt
- src/test/kotlin/no/nb/mlt/wls/item/model/ItemModelValidationTest.kt
- src/test/kotlin/no/nb/mlt/wls/synq/controller/SynqControllerTest.kt
Follows up on #55, and makes the `quantity` and `location` fields within the data non-nullable. This comes with more benefits than downsides, and simplifies the API.
It even removes the strange edge-case of picking an item where the location is null.  
```diff
} else if (location != null) {
location
} else {
-            // Rare edge case. Log it until we can determine if this actually happens in production
-            logger.error {
-                "Item with ID '$hostId' for host '$hostName' without a location was picked. Location was set to 'UNKNOWN'."
-            }
"UNKNOWN"
}
```
> MLT-0086 Item Model Update

- docker/keycloak/import/mlt-local-realm-export.json
- src/main/kotlin/no/nb/mlt/wls/application/hostapi/config/SecurityConfig.kt
- src/main/kotlin/no/nb/mlt/wls/application/synqapi/config/SecurityConfig.kt
- src/test/kotlin/no/nb/mlt/wls/TraillingSlashRedirectTest.kt
- src/test/kotlin/no/nb/mlt/wls/item/controller/ItemControllerTest.kt
- src/test/kotlin/no/nb/mlt/wls/order/controller/OrderControllerTest.kt
- src/test/kotlin/no/nb/mlt/wls/synq/controller/SynqControllerTest.kt
This PR attempts to change the authorization model to use Roles instead of Scopes as advised by Tom. Changes the JWT algorithm to ES256 as recommended by the documentation.
Questions to @tomolse and @anotheroneofthese: 
- Should we validate JWT type? When I was reading up on security with JWT they recommend checking token type is valid, in our case Bearer and not something else.
- How long should we set JWT time/expiry to? Mostly thinking in local setup at the moment, but I think this should be the same in every environment, local, stage, and prod.
> MLT-0080 Change authorization to roles

- src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqController.kt
- src/main/kotlin/no/nb/mlt/wls/infrastructure/synq/SynqOrderPayload.kt
- src/test/kotlin/no/nb/mlt/wls/order/model/OrderModelConversionTest.kt
- src/test/kotlin/no/nb/mlt/wls/synq/controller/SynqControllerTest.kt
Introduced normalization of order IDs to handle prefixed IDs consistently. Updated relevant logic in the SynqController and corresponding tests to use the normalized order IDs. Added a utility function `normalizeOrderId` and addressed potential edge cases in its implementation.
> MLT-121 Fix issues with order IDs from SynQ

- src/main/kotlin/no/nb/mlt/wls/application/hostapi/item/ApiItemPayload.kt
- src/main/kotlin/no/nb/mlt/wls/domain/ports/outbound/InventoryNotifier.kt
- src/main/kotlin/no/nb/mlt/wls/infrastructure/CatalogEventProcessorAdapter.kt
- src/main/kotlin/no/nb/mlt/wls/infrastructure/callbacks/InventoryNotifierAdapter.kt
- src/main/kotlin/no/nb/mlt/wls/infrastructure/callbacks/NotificationItemPayload.kt
- src/main/kotlin/no/nb/mlt/wls/infrastructure/callbacks/NotificationOrderPayload.kt
- src/test/kotlin/no/nb/mlt/wls/infrastructure/CatalogEventProcessorTest.kt
- src/test/kotlin/no/nb/mlt/wls/infrastructure/callbacks/InventoryNotifierAdapterTest.kt
- src/test/kotlin/no/nb/mlt/wls/item/model/ItemModelConversionTest.kt
- src/test/kotlin/no/nb/mlt/wls/order/model/OrderModelConversionTest.kt
- src/test/kotlin/no/nb/mlt/wls/synq/controller/SynqControllerTest.kt
Add missing `messageId` field to the callbacks in inventory notifier methods.
> MLT-145 Add `messageId` to inventory notifier methods

- src/main/kotlin/no/nb/mlt/wls/infrastructure/callbacks/InventoryNotifierAdapter.kt
If a callback url is malformed we will now log an error, and mark event as processed, so our service isn't trying to send callbacks there in a loop
> MLT-184 Ignore malformed callback URLs

- src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqBatchMoveItemPayload.kt
- src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqController.kt
- src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqInventoryReconciliationPayload.kt
- src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqOrderPickingConfirmationPayload.kt
- src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqOrderStatusUpdatePayload.kt
- src/main/kotlin/no/nb/mlt/wls/infrastructure/synq/SynqProductPayload.kt
SynQ has over 180k products with hostName Mavis. Mavis is dead now, and Axiell took over. However, all those objects are still owned by Mavis in SynQ. As changing the data in SynQ might be risky and take time we will instead change SynQ adapter code to convert Axiell → Mavis on the way into SynQ and vice versa. It also requires us to update our internal database, much easier and more manageable, to use Axiell instead of Mavis so duplicate check on the way into Hermes will work correctly, as well as help with orders and shiii…
- Update Hermes adapter to handle Mavis ↔︎ Axiell conversion
- SynQ Gateway forwards Mavis communication to us (should already happen, but doesn’t hurt to check
- Database update script for converting Mavis → Axiell must be prepared and tested in stage
This PR solves …
> MLT-186 Change how Axiell and Mavis are used in SynQ communication

- src/main/kotlin/no/nb/mlt/wls/domain/ports/inbound/GetOrder.kt
The annotation is inaccurate, as this function does not throw this by itself. This and GetItem behave exactly the same.
> MLT-0207 - Remove throws annotation for GetOrder

- src/main/kotlin/no/nb/mlt/wls/infrastructure/email/EmailAdapter.kt
- src/main/resources/templates/email/order.ftl
In cases where item ID contains spaces the `img` tag would have a mangled `src` attribute. ID will now be sanitized for illegal characters. As Noah pointed out alternative solution would involve using a counter.
> MLT-220 Fix QR code embedding in emails

- src/main/kotlin/no/nb/mlt/wls/infrastructure/repositories/event/MongoCatalogEventRepositoryAdapter.kt
- src/main/kotlin/no/nb/mlt/wls/infrastructure/repositories/event/MongoStorageEventRepositoryAdapter.kt
Fixed it for real this time.
Misread the type of `Signal<StorageEvent!>!` as a guarantee that the value would not be null. Turns out it is null when the signal is complete, as it is done processing everything.
This changes the logging to note what event it is working on during mapping, to then later confirm whether the processing was successful. 
An example of the new structure seen in logs:
```
// Example on success
2025-09-24T09:15:09.353+02:00  INFO 52674 --- [Hermes] [ntLoopGroup-3-6] [] i.r.e.MongoStorageEventRepositoryAdapter : Processing storage event to outbox: OrderCreated(createdOrder=Order(hostName=AXIELL, hostOrderId=testOrder-01, status=NOT_STARTED, orderLine=[OrderItem(hostId=testItem-01, status=NOT_STARTED), OrderItem(hostId=testItem-02, status=NOT_STARTED)], …
```
> Update logging again

- src/main/kotlin/no/nb/mlt/wls/infrastructure/email/EmailAdapter.kt
Send order email to Magasintjenesten as the contact person if possible. Better usability for both users and operators as users get confirmation and update emails directly, and operators have direct contact to users
> MLT-235 Send order emails as the contact person if possible
