NationalLibraryOfNorway/warehouse-logistics-service

k8s/prod/wls.yml, k8s/stage/wls.yml, src/main/resources/application.yml
This adds environment variables which allow you to connect to MongoDB. This has been tested against the staging server and should work out of the box. 
With this the k8s configurations has been updated to grab the appropriate secrets from Vault
=> MLT-0020 MongoDB Connection

k8s/prod/wls.yml, k8s/stage/wls.yml
Fixes the deployment being broken due to looking for the wrong secrets
=> MLT-0023 Update secrets with correct names

k8s/prod/wls.yml, k8s/stage/wls.yml
Added missing secrets to deployment definitions
=> Hotfix: missing secrets in deployment

k8s/prod/wls.yml, k8s/stage/wls.yml, src/main/resources/application.yml
Fixed the ingress spec for k8s deployment, added graceful shutdown to spring server
=> Hotfix fix ingress spec in deployment

pom.xml, src/main/kotlin/no/nb/mlt/wls/core/data/synq/SynqError.kt, src/main/kotlin/no/nb/mlt/wls/order/controller/OrderController.kt, src/main/kotlin/no/nb/mlt/wls/order/payloads/SynqOrderPayload.kt, src/main/kotlin/no/nb/mlt/wls/order/repository/OrderRepository.kt, src/main/kotlin/no/nb/mlt/wls/order/service/OrderService.kt, src/main/kotlin/no/nb/mlt/wls/order/service/SynqOrderService.kt, src/main/kotlin/no/nb/mlt/wls/product/repository/ProductRepository.kt, src/main/kotlin/no/nb/mlt/wls/product/service/ProductService.kt, src/main/kotlin/no/nb/mlt/wls/product/service/SynqProductService.kt, src/main/kotlin/no/nb/mlt/wls/product/service/SynqService.kt, src/test/kotlin/no/nb/mlt/wls/controller/ProductControllerTest.kt, src/test/kotlin/no/nb/mlt/wls/product/controller/ProductControllerTest.kt
This PR adds support for processing orders with a RestController. It adds all necessary infrastructure to do so (services, repository, etc.)
=> MLT-0030 Order Controller

src/test/kotlin/no/nb/mlt/wls/product/ProductConvertiontests.kt
One important note is the `toString` call when using the `HostName` to create a `SynqPayload`. That might need to be documented in some way
=> MLT-0033 Add tests for converting payloads between each other

README.md
Fixes the wrong profile references in the README
=> Change Spring Profile references, fixes #22

src/main/kotlin/no/nb/mlt/wls/core/data/HostName.kt, src/main/kotlin/no/nb/mlt/wls/order/controller/OrderController.kt, src/main/kotlin/no/nb/mlt/wls/order/model/Order.kt, src/main/kotlin/no/nb/mlt/wls/order/payloads/SynqOrderPayload.kt, src/main/kotlin/no/nb/mlt/wls/order/service/OrderService.kt, src/main/kotlin/no/nb/mlt/wls/order/service/SynqOrderService.kt, src/test/kotlin/no/nb/mlt/wls/order/controller/OrderControllerTest.kt, src/test/kotlin/no/nb/mlt/wls/order/service/OrderServiceTest.kt
Adds the functionality to get orders from our database.
The assumptions are that you are authenticated with the correct hostname, and that you have an existing order ID
=> MLT-0042 Order GET endpoint

pom.xml, src/main/kotlin/no/nb/mlt/wls/core/data/HostName.kt, src/main/kotlin/no/nb/mlt/wls/core/data/synq/SynqError.kt, src/main/kotlin/no/nb/mlt/wls/order/controller/OrderController.kt, src/main/kotlin/no/nb/mlt/wls/order/model/Order.kt, src/main/kotlin/no/nb/mlt/wls/order/payloads/SynqOrderPayload.kt, src/main/kotlin/no/nb/mlt/wls/order/repository/OrderRepository.kt, src/main/kotlin/no/nb/mlt/wls/order/service/OrderService.kt, src/main/kotlin/no/nb/mlt/wls/order/service/SynqOrderService.kt, src/test/kotlin/no/nb/mlt/wls/order/controller/OrderControllerTest.kt
Allows for order deletion, not fully tested or cleaned up as we will have a workshop tomorrow for this project and will likely rework some functionality.
=> MLT-0039 Deleting orders

README.md, src/main/kotlin/no/nb/mlt/wls/application/hostapi/ExceptionHandler.kt, src/main/kotlin/no/nb/mlt/wls/application/hostapi/config/SecurityConfig.kt, src/main/kotlin/no/nb/mlt/wls/application/hostapi/item/ApiItemPayload.kt, src/main/kotlin/no/nb/mlt/wls/application/hostapi/item/ItemController.kt, src/main/kotlin/no/nb/mlt/wls/application/hostapi/order/ApiOrderPayload.kt, src/main/kotlin/no/nb/mlt/wls/application/hostapi/order/ApiUpdateOrderPayload.kt, src/main/kotlin/no/nb/mlt/wls/application/hostapi/order/OrderController.kt, src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqBatchMoveItemPayload.kt, src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqController.kt, src/main/kotlin/no/nb/mlt/wls/domain/WLSService.kt, src/main/kotlin/no/nb/mlt/wls/infrastructure/callbacks/InventoryNotifierAdapter.kt, src/test/kotlin/no/nb/mlt/wls/item/controller/ItemControllerTest.kt, src/test/kotlin/no/nb/mlt/wls/item/model/ItemModelConversionTest.kt, src/test/kotlin/no/nb/mlt/wls/order/controller/OrderControllerTest.kt, src/test/kotlin/no/nb/mlt/wls/order/model/OrderModelConversionTest.kt, src/test/kotlin/no/nb/mlt/wls/synq/controller/SynqControllerTest.kt, src/test/kotlin/no/nb/mlt/wls/synq/model/SynqModelsTest.kt
This PR adds some needed unit tests and the resulting fixes to the project
=> MLT-0059 Tests for host API endpoints

docker/mongo/mongo-init.js
This is a small fix which fixes the test data being out of date. Also adds an extra item and a test order.
=> MLT-0065 Update Local DB test data

src/main/kotlin/no/nb/mlt/wls/application/hostapi/item/ApiItemPayload.kt, src/main/kotlin/no/nb/mlt/wls/application/hostapi/order/ApiOrderPayload.kt, src/main/kotlin/no/nb/mlt/wls/application/hostapi/order/ApiUpdateOrderPayload.kt, src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqBatchMoveItemPayload.kt, src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqOrderPickingConfirmationPayload.kt, src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqOrderStatusUpdatePayload.kt, src/main/kotlin/no/nb/mlt/wls/domain/model/HostName.kt, src/test/kotlin/no/nb/mlt/wls/TraillingSlashRedirectTest.kt, src/test/kotlin/no/nb/mlt/wls/item/controller/ItemControllerTest.kt, src/test/kotlin/no/nb/mlt/wls/item/model/ItemModelConversionTest.kt, src/test/kotlin/no/nb/mlt/wls/item/model/ItemModelValidationTest.kt, src/test/kotlin/no/nb/mlt/wls/order/controller/OrderControllerTest.kt, src/test/kotlin/no/nb/mlt/wls/order/model/OrderModelConversionTest.kt, src/test/kotlin/no/nb/mlt/wls/order/model/OrderModelValidationTest.kt, src/test/kotlin/no/nb/mlt/wls/synq/model/SynqModelConversionTest.kt, src/test/kotlin/no/nb/mlt/wls/synq/model/SynqModelValidationTest.kt
This PR improves a lot on the testability of the codebase. 
It also moves some of the validation code into the payloads themselves, as seen with the SynqAPI Payloads
=> MLT-0056 Improve testing for callbacks and more

src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqBatchMoveItemPayload.kt, src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqController.kt, src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqOrderPickingConfirmationPayload.kt, src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqOrderStatusUpdatePayload.kt, src/main/kotlin/no/nb/mlt/wls/domain/WLSService.kt, src/main/kotlin/no/nb/mlt/wls/domain/model/Item.kt, src/main/kotlin/no/nb/mlt/wls/domain/model/Order.kt, src/main/kotlin/no/nb/mlt/wls/domain/ports/inbound/MoveItem.kt, src/main/kotlin/no/nb/mlt/wls/domain/ports/outbound/ItemRepository.kt, src/main/kotlin/no/nb/mlt/wls/infrastructure/repositories/item/MongoItemRepository.kt, src/main/kotlin/no/nb/mlt/wls/infrastructure/synq/SynqOrderPayload.kt, src/test/kotlin/no/nb/mlt/wls/synq/controller/SynqControllerTest.kt, src/test/kotlin/no/nb/mlt/wls/synq/model/SynqModelConversionTest.kt, src/test/kotlin/no/nb/mlt/wls/synq/model/SynqModelValidationTest.kt
This PR aims to improve the structure and maintability of the codebase by migrating a bunch of the domain-specific code into the domain models. Formerly these methods/functions are scattered across the service and the controllers. 
While not technically wrong, it is more concise what use-cases each domain model supports when it is collected within itself. new use-cases also naturally come up when writing this way.
=> MLT-0064 Domain improvements

src/main/kotlin/no/nb/mlt/wls/infrastructure/repositories/item/MongoItemRepository.kt
Uses proper Spring Data Mongo syntax, which fixes a suppressed exception which this method was throwing
=> Fix bulk find method in ItemMongoRepository

src/main/kotlin/no/nb/mlt/wls/application/hostapi/order/ApiCreateOrderPayload.kt, src/main/kotlin/no/nb/mlt/wls/application/hostapi/order/ApiOrderPayload.kt, src/main/kotlin/no/nb/mlt/wls/domain/model/Order.kt, src/test/kotlin/no/nb/mlt/wls/order/controller/OrderControllerTest.kt
Excludes the status field when creating orders as this is not required
=> Update OrderLine Swagger examples

src/main/kotlin/no/nb/mlt/wls/infrastructure/callbacks/InventoryNotifierAdapter.kt
Improve error logging in callbacks
=> HotFix: No error logging in callbacks on error

src/main/kotlin/no/nb/mlt/wls/application/hostapi/ExceptionHandler.kt, src/main/kotlin/no/nb/mlt/wls/infrastructure/synq/SynqOrderPayload.kt
Fixes for bugs that prevent sending orders to SynQ
=> MLT-0126 Order Fixes

src/main/kotlin/no/nb/mlt/wls/application/hostapi/order/ApiCreateOrderPayload.kt, src/main/kotlin/no/nb/mlt/wls/application/hostapi/order/ApiOrderPayload.kt, src/main/kotlin/no/nb/mlt/wls/application/hostapi/order/ApiUpdateOrderPayload.kt, src/main/kotlin/no/nb/mlt/wls/application/hostapi/order/OrderController.kt, src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqBatchMoveItemPayload.kt, src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqController.kt, src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqOrderPickingConfirmationPayload.kt, src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqOrderStatusUpdatePayload.kt, src/main/kotlin/no/nb/mlt/wls/domain/NullableNotBlank.kt, src/main/kotlin/no/nb/mlt/wls/domain/ValidHostName.kt, src/main/kotlin/no/nb/mlt/wls/domain/WLSService.kt, src/main/kotlin/no/nb/mlt/wls/domain/model/Order.kt, src/main/kotlin/no/nb/mlt/wls/domain/ports/inbound/MoveItem.kt, src/test/kotlin/no/nb/mlt/wls/domain/WLSServiceTest.kt, src/test/kotlin/no/nb/mlt/wls/order/model/OrderModelValidationTest.kt, src/test/kotlin/no/nb/mlt/wls/synq/model/SynqModelValidationTest.kt
Reworks validation for data objects to use Jakarta. Refactors the test to support this as well
=> MLT-0128 Validation Rework

src/main/kotlin/no/nb/mlt/wls/domain/model/Environment.kt, src/main/kotlin/no/nb/mlt/wls/domain/model/ItemCategory.kt, src/main/kotlin/no/nb/mlt/wls/infrastructure/synq/SynqAutostoreAdapter.kt, src/main/kotlin/no/nb/mlt/wls/infrastructure/synq/SynqProductPayload.kt, src/main/kotlin/no/nb/mlt/wls/infrastructure/synq/SynqStandardAdapter.kt
Might want to change the name to something more specific to an environment
=> MLT-0137 Make FRAGILE an Environment instead of ItemCategory

.github/workflows/deploy-project.yaml
=> HOTFIX: Update deployment to use specific image

.github/workflows/deploy-project.yaml
How is this hot we have not even turned on the oven
=> HOTFIX: Revert removing k8s host url in stage

.github/workflows/deploy-project.yaml
=> HOTFIX: Fix copy-paste error

k8s/prod/wls.yml, k8s/stage/wls.yml
Fix deployment by adding missing env value
=> HOTFIX: Fix deployment files

k8s/prod/wls.yml, k8s/stage/wls.yml, src/main/kotlin/no/nb/mlt/wls/application/hostapi/config/SecurityConfig.kt, src/main/kotlin/no/nb/mlt/wls/application/hostapi/config/SwaggerConfig.kt, src/main/kotlin/no/nb/mlt/wls/application/hostapi/item/ItemController.kt, src/main/kotlin/no/nb/mlt/wls/application/hostapi/order/OrderController.kt, src/main/kotlin/no/nb/mlt/wls/application/synqapi/config/SecurityConfig.kt, src/main/kotlin/no/nb/mlt/wls/application/synqapi/config/SwaggerConfig.kt, src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqController.kt, src/main/resources/application.yml, src/test/kotlin/no/nb/mlt/wls/TraillingSlashRedirectTest.kt, src/test/kotlin/no/nb/mlt/wls/item/controller/ItemControllerTest.kt, src/test/kotlin/no/nb/mlt/wls/order/controller/OrderControllerTest.kt, src/test/kotlin/no/nb/mlt/wls/synq/controller/SynqControllerTest.kt, src/test/resources/application.yml
As we need to change where our app runs in prod, we might as well change it for stage too.
This should change our service to run on hermes path, instead of as a subdomain.
=> Change host and api paths to run in prod

src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqInventoryReconciliationPayload.kt, src/main/kotlin/no/nb/mlt/wls/domain/model/HostName.kt, src/main/kotlin/no/nb/mlt/wls/infrastructure/repositories/event/MongoStorageEvent.kt, src/main/kotlin/no/nb/mlt/wls/infrastructure/repositories/item/MongoItem.kt, src/main/kotlin/no/nb/mlt/wls/infrastructure/synq/SynqProductPayload.kt
Various fixes that make the production deployment nicer
=> MLT-0138 Storage Fixes

src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqBatchMoveItemPayload.kt, src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqController.kt, src/main/kotlin/no/nb/mlt/wls/domain/WLSService.kt, src/main/kotlin/no/nb/mlt/wls/domain/ports/inbound/UpdateItem.kt, src/test/kotlin/no/nb/mlt/wls/TestHelpers.kt, src/test/kotlin/no/nb/mlt/wls/synq/controller/SynqControllerTest.kt, src/test/kotlin/no/nb/mlt/wls/synq/model/SynqModelConversionTest.kt
Required for handling SynQ and AutoStore correctly
=> MLT-0141 Add UpdateItem

src/main/kotlin/no/nb/mlt/wls/infrastructure/synq/SynqProductPayload.kt, src/test/kotlin/no/nb/mlt/wls/item/model/ItemModelConversionTest.kt
Now respects environment as well
=> MLT-0171 Update SynQ Category mappings

src/main/kotlin/no/nb/mlt/wls/domain/WLSService.kt, src/main/kotlin/no/nb/mlt/wls/domain/model/Order.kt, src/main/kotlin/no/nb/mlt/wls/domain/ports/outbound/OrderRepository.kt, src/main/kotlin/no/nb/mlt/wls/infrastructure/repositories/order/MongoOrderRepositoryAdapter.kt, src/test/kotlin/no/nb/mlt/wls/domain/WLSServiceTest.kt
=> MLT-0170 Order return logic

k8s/prod/wls.yml, k8s/stage/wls.yml
Add order handler email to the deployment file
=> HOTFIX: Enable email sending from Hermes

.github/dependabot.yml, .github/workflows/deploy-project.yaml, pom.xml
Includes #172 #171 #170 #169 #168 #165
=> Bump dependencies
